//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAndLoadTestProject12
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;


    public class WebTest1Coded : WebTest
    {

        public WebTest1Coded()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            WebTestRequest request1 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Our-Story/Become-Part-of-Our-Story/jackson-hew" +
                    "itt-franchise/");
            WebTestRequest request1Dependent1 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/Lato/fonts/lato-v11-latin-300.eo" +
                    "t");
            request1Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/Our-Story/Become-Part-of-Our-Story/jackson-hew" +
                        "itt-franchise/"));
            request1Dependent1.QueryStringParameters.Add("", "", false, false);
            request1.DependentRequests.Add(request1Dependent1);
            WebTestRequest request1Dependent2 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/Lato/fonts/lato-v11-latin-regula" +
                    "r.eot");
            request1Dependent2.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/Our-Story/Become-Part-of-Our-Story/jackson-hew" +
                        "itt-franchise/"));
            request1Dependent2.QueryStringParameters.Add("", "", false, false);
            request1.DependentRequests.Add(request1Dependent2);
            WebTestRequest request1Dependent3 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/Lato/fonts/lato-v11-latin-italic" +
                    ".eot");
            request1Dependent3.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/Our-Story/Become-Part-of-Our-Story/jackson-hew" +
                        "itt-franchise/"));
            request1Dependent3.QueryStringParameters.Add("", "", false, false);
            request1.DependentRequests.Add(request1Dependent3);
            WebTestRequest request1Dependent4 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/Lato/fonts/lato-v11-latin-700.eo" +
                    "t");
            request1Dependent4.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/Our-Story/Become-Part-of-Our-Story/jackson-hew" +
                        "itt-franchise/"));
            request1Dependent4.QueryStringParameters.Add("", "", false, false);
            request1.DependentRequests.Add(request1Dependent4);
            WebTestRequest request1Dependent5 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/font-awesome/fonts/fontawesome-w" +
                    "ebfont.eot");
            request1Dependent5.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/Our-Story/Become-Part-of-Our-Story/jackson-hew" +
                        "itt-franchise/"));
            request1Dependent5.QueryStringParameters.Add("", "", false, false);
            request1.DependentRequests.Add(request1Dependent5);
            WebTestRequest request1Dependent6 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/VarelaRound/fonts/varela-round-v" +
                    "6-latin-regular.eot");
            request1Dependent6.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/Our-Story/Become-Part-of-Our-Story/jackson-hew" +
                        "itt-franchise/"));
            request1Dependent6.QueryStringParameters.Add("", "", false, false);
            request1.DependentRequests.Add(request1Dependent6);
            WebTestRequest request1Dependent7 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/jackson-hewitt.eot");
            request1Dependent7.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/Our-Story/Become-Part-of-Our-Story/jackson-hew" +
                        "itt-franchise/"));
            request1Dependent7.QueryStringParameters.Add("", "", false, false);
            request1.DependentRequests.Add(request1Dependent7);
            WebTestRequest request1Dependent8 = new WebTestRequest("https://bs.serving-sys.com/Serving");
            request1Dependent8.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/Our-Story/Become-Part-of-Our-Story/jackson-hew" +
                        "itt-franchise/"));
            request1Dependent8.QueryStringParameters.Add("cn", "ot", false, false);
            request1Dependent8.QueryStringParameters.Add("onetagid", "4398", false, false);
            request1Dependent8.QueryStringParameters.Add("dispType", "js", false, false);
            request1Dependent8.QueryStringParameters.Add("sync", "0", false, false);
            request1Dependent8.QueryStringParameters.Add("pageurl", "$$https%3A//ss-test2.jacksonhewitt.com/Our-Story/Become-Part-of-Our-Story/jackson" +
                    "-hewitt-franchise/$$", false, false);
            request1Dependent8.QueryStringParameters.Add("ns", "0", false, false);
            request1Dependent8.QueryStringParameters.Add("rnd", "8867710252567702", false, false);
            request1.DependentRequests.Add(request1Dependent8);
            WebTestRequest request1Dependent9 = new WebTestRequest("https://bat.r.msn.com/action-uic/0");
            request1Dependent9.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/Our-Story/Become-Part-of-Our-Story/jackson-hew" +
                        "itt-franchise/"));
            request1Dependent9.QueryStringParameters.Add("ti", "5176460", false, false);
            request1Dependent9.QueryStringParameters.Add("Ver", "2", false, false);
            request1Dependent9.QueryStringParameters.Add("mid", "9573cd7b-ff2c-bdab-efe8-b60473900165", false, false);
            request1Dependent9.QueryStringParameters.Add("evt", "pageLoad", false, false);
            request1Dependent9.QueryStringParameters.Add("lt", "11906", false, false);
            request1Dependent9.QueryStringParameters.Add("pi", "576086242", false, false);
            request1Dependent9.QueryStringParameters.Add("lg", "en-US", false, false);
            request1Dependent9.QueryStringParameters.Add("sw", "1600", false, false);
            request1Dependent9.QueryStringParameters.Add("sh", "900", false, false);
            request1Dependent9.QueryStringParameters.Add("sc", "24", false, false);
            request1Dependent9.QueryStringParameters.Add("p", "https%3A%2F%2Fss-test2.jacksonhewitt.com%2FOur-Story%2FBecome-Part-of-Our-Story%2" +
                    "Fjackson-hewitt-franchise%2F", false, false);
            request1Dependent9.QueryStringParameters.Add("r", "", false, false);
            request1Dependent9.QueryStringParameters.Add("rn", "853824", false, false);
            request1.DependentRequests.Add(request1Dependent9);
            WebTestRequest request1Dependent10 = new WebTestRequest("https://bat.bing.com/action/0");
            request1Dependent10.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/Our-Story/Become-Part-of-Our-Story/jackson-hew" +
                        "itt-franchise/"));
            request1Dependent10.QueryStringParameters.Add("ti", "5176460", false, false);
            request1Dependent10.QueryStringParameters.Add("Ver", "2", false, false);
            request1Dependent10.QueryStringParameters.Add("mid", "9573cd7b-ff2c-bdab-efe8-b60473900165", false, false);
            request1Dependent10.QueryStringParameters.Add("evt", "pageLoad", false, false);
            request1Dependent10.QueryStringParameters.Add("lt", "11906", false, false);
            request1Dependent10.QueryStringParameters.Add("pi", "576086242", false, false);
            request1Dependent10.QueryStringParameters.Add("lg", "en-US", false, false);
            request1Dependent10.QueryStringParameters.Add("sw", "1600", false, false);
            request1Dependent10.QueryStringParameters.Add("sh", "900", false, false);
            request1Dependent10.QueryStringParameters.Add("sc", "24", false, false);
            request1Dependent10.QueryStringParameters.Add("p", "https%3A%2F%2Fss-test2.jacksonhewitt.com%2FOur-Story%2FBecome-Part-of-Our-Story%2" +
                    "Fjackson-hewitt-franchise%2F", false, false);
            request1Dependent10.QueryStringParameters.Add("r", "", false, false);
            request1Dependent10.QueryStringParameters.Add("rn", "46792", false, false);
            request1.DependentRequests.Add(request1Dependent10);
            WebTestRequest request1Dependent11 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/Lato/fonts/lato-v11-latin-300.wo" +
                    "ff");
            request1Dependent11.ThinkTime = 3;
            request1Dependent11.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/Our-Story/Become-Part-of-Our-Story/jackson-hew" +
                        "itt-franchise/"));
            request1.DependentRequests.Add(request1Dependent11);
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Offers/About-Jackson-Hewitt/");
            request2.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/Our-Story/Become-Part-of-Our-Story/jackson-hew" +
                        "itt-franchise/"));
            WebTestRequest request2Dependent1 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/Lato/fonts/lato-v11-latin-300.eo" +
                    "t");
            request2Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/Offers/About-Jackson-Hewitt/"));
            request2Dependent1.QueryStringParameters.Add("", "", false, false);
            request2.DependentRequests.Add(request2Dependent1);
            WebTestRequest request2Dependent2 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/Lato/fonts/lato-v11-latin-regula" +
                    "r.eot");
            request2Dependent2.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/Offers/About-Jackson-Hewitt/"));
            request2Dependent2.QueryStringParameters.Add("", "", false, false);
            request2.DependentRequests.Add(request2Dependent2);
            WebTestRequest request2Dependent3 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/Lato/fonts/lato-v11-latin-italic" +
                    ".eot");
            request2Dependent3.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/Offers/About-Jackson-Hewitt/"));
            request2Dependent3.QueryStringParameters.Add("", "", false, false);
            request2.DependentRequests.Add(request2Dependent3);
            WebTestRequest request2Dependent4 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/Lato/fonts/lato-v11-latin-700.eo" +
                    "t");
            request2Dependent4.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/Offers/About-Jackson-Hewitt/"));
            request2Dependent4.QueryStringParameters.Add("", "", false, false);
            request2.DependentRequests.Add(request2Dependent4);
            WebTestRequest request2Dependent5 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/font-awesome/fonts/fontawesome-w" +
                    "ebfont.eot");
            request2Dependent5.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/Offers/About-Jackson-Hewitt/"));
            request2Dependent5.QueryStringParameters.Add("", "", false, false);
            request2.DependentRequests.Add(request2Dependent5);
            WebTestRequest request2Dependent6 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/VarelaRound/fonts/varela-round-v" +
                    "6-latin-regular.eot");
            request2Dependent6.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/Offers/About-Jackson-Hewitt/"));
            request2Dependent6.QueryStringParameters.Add("", "", false, false);
            request2.DependentRequests.Add(request2Dependent6);
            WebTestRequest request2Dependent7 = new WebTestRequest("https://bs.serving-sys.com/Serving");
            request2Dependent7.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/Offers/About-Jackson-Hewitt/"));
            request2Dependent7.QueryStringParameters.Add("cn", "ot", false, false);
            request2Dependent7.QueryStringParameters.Add("onetagid", "4398", false, false);
            request2Dependent7.QueryStringParameters.Add("dispType", "js", false, false);
            request2Dependent7.QueryStringParameters.Add("sync", "0", false, false);
            request2Dependent7.QueryStringParameters.Add("pageurl", "$$https%3A//ss-test2.jacksonhewitt.com/Offers/About-Jackson-Hewitt/$$", false, false);
            request2Dependent7.QueryStringParameters.Add("ns", "0", false, false);
            request2Dependent7.QueryStringParameters.Add("rnd", "01979361301374366", false, false);
            request2Dependent7.QueryStringParameters.Add("referrer", "$$https://ss-test2.jacksonhewitt.com/Our-Story/Become-Part-of-Our-Story/jackson-h" +
                    "ewitt-franchise/$$", false, false);
            request2.DependentRequests.Add(request2Dependent7);
            WebTestRequest request2Dependent8 = new WebTestRequest("https://bat.r.msn.com/action-uic/0");
            request2Dependent8.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/Offers/About-Jackson-Hewitt/"));
            request2Dependent8.QueryStringParameters.Add("ti", "5176460", false, false);
            request2Dependent8.QueryStringParameters.Add("Ver", "2", false, false);
            request2Dependent8.QueryStringParameters.Add("mid", "0eccf662-57b3-462b-171f-2dddcacad339", false, false);
            request2Dependent8.QueryStringParameters.Add("evt", "pageLoad", false, false);
            request2Dependent8.QueryStringParameters.Add("lt", "556", false, false);
            request2Dependent8.QueryStringParameters.Add("pi", "576086242", false, false);
            request2Dependent8.QueryStringParameters.Add("lg", "en-US", false, false);
            request2Dependent8.QueryStringParameters.Add("sw", "1600", false, false);
            request2Dependent8.QueryStringParameters.Add("sh", "900", false, false);
            request2Dependent8.QueryStringParameters.Add("sc", "24", false, false);
            request2Dependent8.QueryStringParameters.Add("r", "https%3A%2F%2Fss-test2.jacksonhewitt.com%2FOur-Story%2FBecome-Part-of-Our-Story%2" +
                    "Fjackson-hewitt-franchise%2F", false, false);
            request2Dependent8.QueryStringParameters.Add("p", "https%3A%2F%2Fss-test2.jacksonhewitt.com%2FOffers%2FAbout-Jackson-Hewitt%2F", false, false);
            request2Dependent8.QueryStringParameters.Add("rn", "146602", false, false);
            request2.DependentRequests.Add(request2Dependent8);
            WebTestRequest request2Dependent9 = new WebTestRequest("https://bat.bing.com/action/0");
            request2Dependent9.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/Offers/About-Jackson-Hewitt/"));
            request2Dependent9.QueryStringParameters.Add("ti", "5176460", false, false);
            request2Dependent9.QueryStringParameters.Add("Ver", "2", false, false);
            request2Dependent9.QueryStringParameters.Add("mid", "0eccf662-57b3-462b-171f-2dddcacad339", false, false);
            request2Dependent9.QueryStringParameters.Add("evt", "pageLoad", false, false);
            request2Dependent9.QueryStringParameters.Add("lt", "556", false, false);
            request2Dependent9.QueryStringParameters.Add("pi", "576086242", false, false);
            request2Dependent9.QueryStringParameters.Add("lg", "en-US", false, false);
            request2Dependent9.QueryStringParameters.Add("sw", "1600", false, false);
            request2Dependent9.QueryStringParameters.Add("sh", "900", false, false);
            request2Dependent9.QueryStringParameters.Add("sc", "24", false, false);
            request2Dependent9.QueryStringParameters.Add("r", "https%3A%2F%2Fss-test2.jacksonhewitt.com%2FOur-Story%2FBecome-Part-of-Our-Story%2" +
                    "Fjackson-hewitt-franchise%2F", false, false);
            request2Dependent9.QueryStringParameters.Add("p", "https%3A%2F%2Fss-test2.jacksonhewitt.com%2FOffers%2FAbout-Jackson-Hewitt%2F", false, false);
            request2Dependent9.QueryStringParameters.Add("rn", "368764", false, false);
            request2.DependentRequests.Add(request2Dependent9);
            WebTestRequest request2Dependent10 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/Lato/fonts/lato-v11-latin-300.wo" +
                    "ff");
            request2Dependent10.ThinkTime = 8;
            request2Dependent10.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/Offers/About-Jackson-Hewitt/"));
            request2.DependentRequests.Add(request2Dependent10);
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/file-taxes-online/");
            request3.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/Offers/About-Jackson-Hewitt/"));
            WebTestRequest request3Dependent1 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/Lato/fonts/lato-v11-latin-300.eo" +
                    "t");
            request3Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/file-taxes-online/"));
            request3Dependent1.QueryStringParameters.Add("", "", false, false);
            request3.DependentRequests.Add(request3Dependent1);
            WebTestRequest request3Dependent2 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/Lato/fonts/lato-v11-latin-italic" +
                    ".eot");
            request3Dependent2.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/file-taxes-online/"));
            request3Dependent2.QueryStringParameters.Add("", "", false, false);
            request3.DependentRequests.Add(request3Dependent2);
            WebTestRequest request3Dependent3 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/Lato/fonts/lato-v11-latin-regula" +
                    "r.eot");
            request3Dependent3.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/file-taxes-online/"));
            request3Dependent3.QueryStringParameters.Add("", "", false, false);
            request3.DependentRequests.Add(request3Dependent3);
            WebTestRequest request3Dependent4 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/Lato/fonts/lato-v11-latin-700.eo" +
                    "t");
            request3Dependent4.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/file-taxes-online/"));
            request3Dependent4.QueryStringParameters.Add("", "", false, false);
            request3.DependentRequests.Add(request3Dependent4);
            WebTestRequest request3Dependent5 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/font-awesome/fonts/fontawesome-w" +
                    "ebfont.eot");
            request3Dependent5.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/file-taxes-online/"));
            request3Dependent5.QueryStringParameters.Add("", "", false, false);
            request3.DependentRequests.Add(request3Dependent5);
            WebTestRequest request3Dependent6 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/VarelaRound/fonts/varela-round-v" +
                    "6-latin-regular.eot");
            request3Dependent6.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/file-taxes-online/"));
            request3Dependent6.QueryStringParameters.Add("", "", false, false);
            request3.DependentRequests.Add(request3Dependent6);
            WebTestRequest request3Dependent7 = new WebTestRequest("https://bs.serving-sys.com/Serving");
            request3Dependent7.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/file-taxes-online/"));
            request3Dependent7.QueryStringParameters.Add("cn", "ot", false, false);
            request3Dependent7.QueryStringParameters.Add("onetagid", "4398", false, false);
            request3Dependent7.QueryStringParameters.Add("dispType", "js", false, false);
            request3Dependent7.QueryStringParameters.Add("sync", "0", false, false);
            request3Dependent7.QueryStringParameters.Add("pageurl", "$$https%3A//ss-test2.jacksonhewitt.com/file-taxes-online/$$", false, false);
            request3Dependent7.QueryStringParameters.Add("ns", "0", false, false);
            request3Dependent7.QueryStringParameters.Add("rnd", "8873741471678753", false, false);
            request3Dependent7.QueryStringParameters.Add("referrer", "$$https://ss-test2.jacksonhewitt.com/Offers/About-Jackson-Hewitt/$$", false, false);
            request3.DependentRequests.Add(request3Dependent7);
            WebTestRequest request3Dependent8 = new WebTestRequest("https://bat.r.msn.com/action-uic/0");
            request3Dependent8.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/file-taxes-online/"));
            request3Dependent8.QueryStringParameters.Add("ti", "5176460", false, false);
            request3Dependent8.QueryStringParameters.Add("Ver", "2", false, false);
            request3Dependent8.QueryStringParameters.Add("mid", "d6538606-99dd-11a6-192c-2932047a3a6a", false, false);
            request3Dependent8.QueryStringParameters.Add("evt", "pageLoad", false, false);
            request3Dependent8.QueryStringParameters.Add("lt", "2379", false, false);
            request3Dependent8.QueryStringParameters.Add("pi", "576086242", false, false);
            request3Dependent8.QueryStringParameters.Add("lg", "en-US", false, false);
            request3Dependent8.QueryStringParameters.Add("sw", "1600", false, false);
            request3Dependent8.QueryStringParameters.Add("sh", "900", false, false);
            request3Dependent8.QueryStringParameters.Add("sc", "24", false, false);
            request3Dependent8.QueryStringParameters.Add("r", "https%3A%2F%2Fss-test2.jacksonhewitt.com%2FOffers%2FAbout-Jackson-Hewitt%2F", false, false);
            request3Dependent8.QueryStringParameters.Add("p", "https%3A%2F%2Fss-test2.jacksonhewitt.com%2Ffile-taxes-online%2F", false, false);
            request3Dependent8.QueryStringParameters.Add("rn", "8186", false, false);
            request3.DependentRequests.Add(request3Dependent8);
            WebTestRequest request3Dependent9 = new WebTestRequest("https://bat.bing.com/action/0");
            request3Dependent9.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/file-taxes-online/"));
            request3Dependent9.QueryStringParameters.Add("ti", "5176460", false, false);
            request3Dependent9.QueryStringParameters.Add("Ver", "2", false, false);
            request3Dependent9.QueryStringParameters.Add("mid", "d6538606-99dd-11a6-192c-2932047a3a6a", false, false);
            request3Dependent9.QueryStringParameters.Add("evt", "pageLoad", false, false);
            request3Dependent9.QueryStringParameters.Add("lt", "2379", false, false);
            request3Dependent9.QueryStringParameters.Add("pi", "576086242", false, false);
            request3Dependent9.QueryStringParameters.Add("lg", "en-US", false, false);
            request3Dependent9.QueryStringParameters.Add("sw", "1600", false, false);
            request3Dependent9.QueryStringParameters.Add("sh", "900", false, false);
            request3Dependent9.QueryStringParameters.Add("sc", "24", false, false);
            request3Dependent9.QueryStringParameters.Add("r", "https%3A%2F%2Fss-test2.jacksonhewitt.com%2FOffers%2FAbout-Jackson-Hewitt%2F", false, false);
            request3Dependent9.QueryStringParameters.Add("p", "https%3A%2F%2Fss-test2.jacksonhewitt.com%2Ffile-taxes-online%2F", false, false);
            request3Dependent9.QueryStringParameters.Add("rn", "212251", false, false);
            request3.DependentRequests.Add(request3Dependent9);
            WebTestRequest request3Dependent10 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/Lato/fonts/lato-v11-latin-300.wo" +
                    "ff");
            request3Dependent10.ThinkTime = 2;
            request3Dependent10.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/file-taxes-online/"));
            request3.DependentRequests.Add(request3Dependent10);
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/File-Taxes-Online-Conversion/");
            request4.QueryStringParameters.Add("destinationUrl", "/welcome/essential-documents/?package=free", false, false);
            request4.QueryStringParameters.Add("source", "jho", false, false);
            request4.QueryStringParameters.Add("newaccount", "true", false, false);
            yield return request4;
            request4 = null;

            WebTestRequest request5 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/File-Taxes-Online-Conversion/");
            request5.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/file-taxes-online/"));
            request5.QueryStringParameters.Add("destinationUrl", "/welcome/essential-documents/?package%3dfree", false, false);
            request5.QueryStringParameters.Add("source", "jho", false, false);
            request5.QueryStringParameters.Add("newaccount", "true", false, false);
            yield return request5;
            request5 = null;

            WebTestRequest request6 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/welcome/essential-documents/");
            request6.ExpectedResponseUrl = "https://test-accounts.jacksonhewitt.com/Account/SignUp";
            request6.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/File-Taxes-Online-Conversion/?destinationUrl=/" +
                        "welcome/essential-documents/?package=free&source=jho&newaccount=true"));
            request6.QueryStringParameters.Add("package", "free", false, false);
            request6.QueryStringParameters.Add("source", "jho", false, false);
            request6.QueryStringParameters.Add("newaccount", "true", false, false);
            WebTestRequest request6Dependent1 = new WebTestRequest("https://fonts.googleapis.com/css");
            request6Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "https://test-accounts.jacksonhewitt.com/Account/SignUp"));
            request6Dependent1.QueryStringParameters.Add("family", "Lato:400italic,700italic,300,400,700|Varela+Round", false, false);
            request6.DependentRequests.Add(request6Dependent1);
            yield return request6;
            request6 = null;

            WebTestRequest request7 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/font-awesome/fonts/fontawesome-w" +
                    "ebfont.eot");
            request7.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/File-Taxes-Online-Conversion/?destinationUrl=/" +
                        "welcome/essential-documents/?package=free&source=jho&newaccount=true"));
            request7.QueryStringParameters.Add("", "", false, false);
            yield return request7;
            request7 = null;

            WebTestRequest request8 = new WebTestRequest("https://bat.r.msn.com/action-uic/0");
            request8.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/File-Taxes-Online-Conversion/?destinationUrl=/" +
                        "welcome/essential-documents/?package=free&source=jho&newaccount=true"));
            request8.QueryStringParameters.Add("ti", "5176460", false, false);
            request8.QueryStringParameters.Add("Ver", "2", false, false);
            request8.QueryStringParameters.Add("mid", "c6e016d2-ea42-473c-b2e6-745aea91cfb8", false, false);
            request8.QueryStringParameters.Add("evt", "pageLoad", false, false);
            request8.QueryStringParameters.Add("pi", "576086242", false, false);
            request8.QueryStringParameters.Add("lg", "en-US", false, false);
            request8.QueryStringParameters.Add("sw", "1600", false, false);
            request8.QueryStringParameters.Add("sh", "900", false, false);
            request8.QueryStringParameters.Add("sc", "24", false, false);
            request8.QueryStringParameters.Add("r", "https%3A%2F%2Fss-test2.jacksonhewitt.com%2Ffile-taxes-online%2F", false, false);
            request8.QueryStringParameters.Add("p", "https%3A%2F%2Fss-test2.jacksonhewitt.com%2FFile-Taxes-Online-Conversion%2F%3Fdest" +
                    "inationUrl%3D%2Fwelcome%2Fessential-documents%2F%3Fpackage%3Dfree%26source%3Djho" +
                    "%26newaccount%3Dtrue", false, false);
            request8.QueryStringParameters.Add("rn", "251723", false, false);
            yield return request8;
            request8 = null;

            WebTestRequest request9 = new WebTestRequest("https://bat.bing.com/action/0");
            request9.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/File-Taxes-Online-Conversion/?destinationUrl=/" +
                        "welcome/essential-documents/?package=free&source=jho&newaccount=true"));
            request9.QueryStringParameters.Add("ti", "5176460", false, false);
            request9.QueryStringParameters.Add("Ver", "2", false, false);
            request9.QueryStringParameters.Add("mid", "c6e016d2-ea42-473c-b2e6-745aea91cfb8", false, false);
            request9.QueryStringParameters.Add("evt", "pageLoad", false, false);
            request9.QueryStringParameters.Add("pi", "576086242", false, false);
            request9.QueryStringParameters.Add("lg", "en-US", false, false);
            request9.QueryStringParameters.Add("sw", "1600", false, false);
            request9.QueryStringParameters.Add("sh", "900", false, false);
            request9.QueryStringParameters.Add("sc", "24", false, false);
            request9.QueryStringParameters.Add("r", "https%3A%2F%2Fss-test2.jacksonhewitt.com%2Ffile-taxes-online%2F", false, false);
            request9.QueryStringParameters.Add("p", "https%3A%2F%2Fss-test2.jacksonhewitt.com%2FFile-Taxes-Online-Conversion%2F%3Fdest" +
                    "inationUrl%3D%2Fwelcome%2Fessential-documents%2F%3Fpackage%3Dfree%26source%3Djho" +
                    "%26newaccount%3Dtrue", false, false);
            request9.QueryStringParameters.Add("rn", "871412", false, false);
            yield return request9;
            request9 = null;

            WebTestRequest request10 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/Lato/fonts/lato-v11-latin-300.wo" +
                    "ff");
            request10.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/File-Taxes-Online-Conversion/?destinationUrl=/" +
                        "welcome/essential-documents/?package=free&source=jho&newaccount=true"));
            yield return request10;
            request10 = null;

            WebTestRequest request11 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/Lato/fonts/lato-v11-latin-regula" +
                    "r.woff");
            request11.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/File-Taxes-Online-Conversion/?destinationUrl=/" +
                        "welcome/essential-documents/?package=free&source=jho&newaccount=true"));
            yield return request11;
            request11 = null;

            WebTestRequest request12 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/Lato/fonts/lato-v11-latin-italic" +
                    ".woff");
            request12.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/File-Taxes-Online-Conversion/?destinationUrl=/" +
                        "welcome/essential-documents/?package=free&source=jho&newaccount=true"));
            yield return request12;
            request12 = null;

            WebTestRequest request13 = new WebTestRequest("https://ss-test2.jacksonhewitt.com/Content/Fonts/Lato/fonts/lato-v11-latin-700.wo" +
                    "ff");
            request13.ThinkTime = 7;
            request13.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test2.jacksonhewitt.com/File-Taxes-Online-Conversion/?destinationUrl=/" +
                        "welcome/essential-documents/?package=free&source=jho&newaccount=true"));
            yield return request13;
            request13 = null;

            WebTestRequest request14 = new WebTestRequest("https://bs.serving-sys.com/Serving/ActivityServer.bs");
            request14.Headers.Add(new WebTestRequestHeader("Referer", "https://test-accounts.jacksonhewitt.com/Account/SignUp"));
            request14.QueryStringParameters.Add("cn", "as", false, false);
            request14.QueryStringParameters.Add("ActivityID", "575239", false, false);
            request14.QueryStringParameters.Add("rnd", "745900.9930209021", false, false);
            yield return request14;
            request14 = null;

            WebTestRequest request15 = new WebTestRequest("https://ss-test.jacksonhewitt.com/termsofusegeneric.aspx");
            request15.Headers.Add(new WebTestRequestHeader("Referer", "https://test-accounts.jacksonhewitt.com/Account/SignUp"));
            WebTestRequest request15Dependent1 = new WebTestRequest("https://fonts.googleapis.com/css");
            request15Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test.jacksonhewitt.com/termsofusegeneric.aspx"));
            request15Dependent1.QueryStringParameters.Add("family", "Lato:300,400,700|Varela+Round", false, false);
            request15.DependentRequests.Add(request15Dependent1);
            yield return request15;
            request15 = null;

            WebTestRequest request16 = new WebTestRequest("https://fonts.gstatic.com/s/lato/v11/KT3KS9Aol4WfR6Vas8kNcg.woff");
            request16.Headers.Add(new WebTestRequestHeader("Referer", "https://test-accounts.jacksonhewitt.com/Account/SignUp"));
            yield return request16;
            request16 = null;

            WebTestRequest request17 = new WebTestRequest("https://fonts.gstatic.com/s/lato/v11/9k-RPmcnxYEPm8CNFsH2gg.woff");
            request17.Headers.Add(new WebTestRequestHeader("Referer", "https://test-accounts.jacksonhewitt.com/Account/SignUp"));
            yield return request17;
            request17 = null;

            WebTestRequest request18 = new WebTestRequest("https://fonts.gstatic.com/s/lato/v11/wkfQbvfT_02e2IWO3yYueQ.woff");
            request18.Headers.Add(new WebTestRequestHeader("Referer", "https://test-accounts.jacksonhewitt.com/Account/SignUp"));
            yield return request18;
            request18 = null;

            WebTestRequest request19 = new WebTestRequest("https://fonts.gstatic.com/s/lato/v11/oUan5VrEkpzIazlUe5ieaA.woff");
            request19.Headers.Add(new WebTestRequestHeader("Referer", "https://test-accounts.jacksonhewitt.com/Account/SignUp"));
            yield return request19;
            request19 = null;

            WebTestRequest request20 = new WebTestRequest("https://fonts.gstatic.com/s/lato/v11/HkF_qI1x_noxlxhrhMQYED8E0i7KZn-EPnyo3HZu7kw." +
                    "woff");
            request20.Headers.Add(new WebTestRequestHeader("Referer", "https://test-accounts.jacksonhewitt.com/Account/SignUp"));
            yield return request20;
            request20 = null;

            WebTestRequest request21 = new WebTestRequest("https://www.google.com/recaptcha/api2/anchor");
            request21.Headers.Add(new WebTestRequestHeader("Referer", "https://test-accounts.jacksonhewitt.com/Account/SignUp"));
            request21.QueryStringParameters.Add("k", "6LddFxQTAAAAAIv-3vX-Z4IxTqQMUNYeGlExx8cc", false, false);
            request21.QueryStringParameters.Add("co", "aHR0cHM6Ly90ZXN0LWFjY291bnRzLmphY2tzb25oZXdpdHQuY29tOjQ0Mw..", false, false);
            request21.QueryStringParameters.Add("hl", "en", false, false);
            request21.QueryStringParameters.Add("v", "r20160706101427", false, false);
            request21.QueryStringParameters.Add("size", "normal", false, false);
            request21.QueryStringParameters.Add("cb", "e19yhq1gqp7i", false, false);
            yield return request21;
            request21 = null;

            WebTestRequest request22 = new WebTestRequest("https://ss-test.jacksonhewitt.com/privacypolicygeneric.aspx");
            request22.Headers.Add(new WebTestRequestHeader("Referer", "https://test-accounts.jacksonhewitt.com/Account/SignUp"));
            WebTestRequest request22Dependent1 = new WebTestRequest("https://fonts.googleapis.com/css");
            request22Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test.jacksonhewitt.com/privacypolicygeneric.aspx"));
            request22Dependent1.QueryStringParameters.Add("family", "Lato:300,400,700|Varela+Round", false, false);
            request22.DependentRequests.Add(request22Dependent1);
            yield return request22;
            request22 = null;

            WebTestRequest request23 = new WebTestRequest("https://googleads.g.doubleclick.net/pagead/viewthroughconversion/963471823/");
            request23.ExpectedResponseUrl = "https://www.google.com/ads/user-lists/963471823/?fmt=1&num=1&cv=8&frm=1&url=https" +
                "%3A//test-accounts.jacksonhewitt.com/Account/SignUp&random=4203513635";
            request23.Headers.Add(new WebTestRequestHeader("Referer", "https://test-accounts.jacksonhewitt.com/Account/SignUp"));
            request23.QueryStringParameters.Add("random", "1468011146238", false, false);
            request23.QueryStringParameters.Add("cv", "8", false, false);
            request23.QueryStringParameters.Add("fst", "1468011146238", false, false);
            request23.QueryStringParameters.Add("num", "1", false, false);
            request23.QueryStringParameters.Add("fmt", "1", false, false);
            request23.QueryStringParameters.Add("guid", "ON", false, false);
            request23.QueryStringParameters.Add("u_h", "900", false, false);
            request23.QueryStringParameters.Add("u_w", "1600", false, false);
            request23.QueryStringParameters.Add("u_ah", "860", false, false);
            request23.QueryStringParameters.Add("u_aw", "1600", false, false);
            request23.QueryStringParameters.Add("u_cd", "24", false, false);
            request23.QueryStringParameters.Add("u_his", "4", false, false);
            request23.QueryStringParameters.Add("u_tz", "-240", false, false);
            request23.QueryStringParameters.Add("u_java", "true", false, false);
            request23.QueryStringParameters.Add("u_nplug", "2", false, false);
            request23.QueryStringParameters.Add("u_nmime", "4", false, false);
            request23.QueryStringParameters.Add("frm", "1", false, false);
            request23.QueryStringParameters.Add("url", "https%3A//test-accounts.jacksonhewitt.com/Account/SignUp", false, false);
            yield return request23;
            request23 = null;

            WebTestRequest request24 = new WebTestRequest("https://ss-test.jacksonhewitt.com/eulageneric.aspx");
            request24.Headers.Add(new WebTestRequestHeader("Referer", "https://test-accounts.jacksonhewitt.com/Account/SignUp"));
            WebTestRequest request24Dependent1 = new WebTestRequest("https://fonts.googleapis.com/css");
            request24Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "https://ss-test.jacksonhewitt.com/eulageneric.aspx"));
            request24Dependent1.QueryStringParameters.Add("family", "Lato:300,400,700|Varela+Round", false, false);
            request24.DependentRequests.Add(request24Dependent1);
            yield return request24;
            request24 = null;

            WebTestRequest request25 = new WebTestRequest("https://fonts.gstatic.com/s/varelaround/v7/APH4jr0uSos5wiut5cpjrnhCUOGz7vYGh680lG" +
                    "h-uXM.woff");
            request25.Headers.Add(new WebTestRequestHeader("Referer", "https://test-accounts.jacksonhewitt.com/Account/SignUp"));
            yield return request25;
            request25 = null;

            WebTestRequest request26 = new WebTestRequest("https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/fonts/fontawesome-webfont.eot");
            request26.Headers.Add(new WebTestRequestHeader("Referer", "https://test-accounts.jacksonhewitt.com/Account/SignUp"));
            request26.QueryStringParameters.Add("", "", false, false);
            yield return request26;
            request26 = null;

            WebTestRequest request27 = new WebTestRequest("https://bat.r.msn.com/action-uic/0");
            request27.Headers.Add(new WebTestRequestHeader("Referer", "https://test-accounts.jacksonhewitt.com/Account/SignUp"));
            request27.QueryStringParameters.Add("ti", "5176460", false, false);
            request27.QueryStringParameters.Add("Ver", "2", false, false);
            request27.QueryStringParameters.Add("mid", "dc0b6fdd-2d3d-bb15-01ab-c810c7d7e9ad", false, false);
            request27.QueryStringParameters.Add("evt", "pageLoad", false, false);
            request27.QueryStringParameters.Add("pi", "576086242", false, false);
            request27.QueryStringParameters.Add("lg", "en-US", false, false);
            request27.QueryStringParameters.Add("sw", "1600", false, false);
            request27.QueryStringParameters.Add("sh", "900", false, false);
            request27.QueryStringParameters.Add("sc", "24", false, false);
            request27.QueryStringParameters.Add("r", "https%3A%2F%2Fss-test2.jacksonhewitt.com%2FFile-Taxes-Online-Conversion%2F", false, false);
            request27.QueryStringParameters.Add("tl", "Create+Account+|+Jackson+Hewitt+Tax+Service", false, false);
            request27.QueryStringParameters.Add("p", "https%3A%2F%2Ftest-accounts.jacksonhewitt.com%2FAccount%2FSignUp", false, false);
            request27.QueryStringParameters.Add("rn", "760545", false, false);
            yield return request27;
            request27 = null;

            WebTestRequest request28 = new WebTestRequest("https://bat.bing.com/action/0");
            request28.Headers.Add(new WebTestRequestHeader("Referer", "https://test-accounts.jacksonhewitt.com/Account/SignUp"));
            request28.QueryStringParameters.Add("ti", "5176460", false, false);
            request28.QueryStringParameters.Add("Ver", "2", false, false);
            request28.QueryStringParameters.Add("mid", "dc0b6fdd-2d3d-bb15-01ab-c810c7d7e9ad", false, false);
            request28.QueryStringParameters.Add("evt", "pageLoad", false, false);
            request28.QueryStringParameters.Add("pi", "576086242", false, false);
            request28.QueryStringParameters.Add("lg", "en-US", false, false);
            request28.QueryStringParameters.Add("sw", "1600", false, false);
            request28.QueryStringParameters.Add("sh", "900", false, false);
            request28.QueryStringParameters.Add("sc", "24", false, false);
            request28.QueryStringParameters.Add("r", "https%3A%2F%2Fss-test2.jacksonhewitt.com%2FFile-Taxes-Online-Conversion%2F", false, false);
            request28.QueryStringParameters.Add("tl", "Create+Account+|+Jackson+Hewitt+Tax+Service", false, false);
            request28.QueryStringParameters.Add("p", "https%3A%2F%2Ftest-accounts.jacksonhewitt.com%2FAccount%2FSignUp", false, false);
            request28.QueryStringParameters.Add("rn", "950945", false, false);
            yield return request28;
            request28 = null;

            WebTestRequest request29 = new WebTestRequest("https://bs.serving-sys.com/Serving");
            request29.Headers.Add(new WebTestRequestHeader("Referer", "https://test-accounts.jacksonhewitt.com/Account/SignUp"));
            request29.QueryStringParameters.Add("cn", "ot", false, false);
            request29.QueryStringParameters.Add("onetagid", "4398", false, false);
            request29.QueryStringParameters.Add("dispType", "js", false, false);
            request29.QueryStringParameters.Add("sync", "0", false, false);
            request29.QueryStringParameters.Add("pageurl", "$$https%3A//test-accounts.jacksonhewitt.com/Account/SignUp$$", false, false);
            request29.QueryStringParameters.Add("ns", "0", false, false);
            request29.QueryStringParameters.Add("rnd", "2843087350936731", false, false);
            request29.QueryStringParameters.Add("referrer", "$$https://ss-test2.jacksonhewitt.com/File-Taxes-Online-Conversion/?destinationUrl" +
                    "%3d/welcome/essential-documents/?package%3dfree", false, false);
            request29.QueryStringParameters.Add("source", "jho", false, false);
            request29.QueryStringParameters.Add("newaccount", "true$$", false, false);
            yield return request29;
            request29 = null;

            WebTestRequest request30 = new WebTestRequest("https://1179.xg4ken.com/media/redir.php");
            request30.Headers.Add(new WebTestRequestHeader("Referer", "https://test-accounts.jacksonhewitt.com/Account/SignUp"));
            request30.QueryStringParameters.Add("track", "1", false, false);
            request30.QueryStringParameters.Add("token", "78f32a9c-1921-4c59-80b4-1f0f219e90e0", false, false);
            request30.QueryStringParameters.Add("type", "registrationstart2016", false, false);
            request30.QueryStringParameters.Add("val", "0.0", false, false);
            request30.QueryStringParameters.Add("orderId", "", false, false);
            request30.QueryStringParameters.Add("promoCode", "", false, false);
            request30.QueryStringParameters.Add("valueCurrency", "USD", false, false);
            request30.QueryStringParameters.Add("GCID", "", false, false);
            request30.QueryStringParameters.Add("kw", "", false, false);
            request30.QueryStringParameters.Add("product", "", false, false);
            yield return request30;
            request30 = null;

            WebTestRequest request31 = new WebTestRequest("https://centro.pixel.ad/iap/97aa78d3794540ba");
            request31.ExpectedResponseUrl = "https://pixel.sitescout.com/iap/97aa78d3794540ba";
            request31.Headers.Add(new WebTestRequestHeader("Referer", "https://test-accounts.jacksonhewitt.com/Account/SignUp"));
            yield return request31;
            request31 = null;

            WebTestRequest request32 = new WebTestRequest("https://fonts.gstatic.com/s/roboto/v15/zN7GBFwfMP4uA6AR0HCoLQ.ttf");
            request32.Headers.Add(new WebTestRequestHeader("Referer", "https://www.google.com/recaptcha/api2/anchor?k=6LddFxQTAAAAAIv-3vX-Z4IxTqQMUNYeGl" +
                        "Exx8cc&co=aHR0cHM6Ly90ZXN0LWFjY291bnRzLmphY2tzb25oZXdpdHQuY29tOjQ0Mw..&hl=en&v=r" +
                        "20160706101427&size=normal&cb=e19yhq1gqp7i"));
            yield return request32;
            request32 = null;

            WebTestRequest request33 = new WebTestRequest("https://fonts.gstatic.com/s/roboto/v15/RxZJdnzeo3R5zSexge8UUaCWcynf_cDxXwCLxiixG1" +
                    "c.ttf");
            request33.Headers.Add(new WebTestRequestHeader("Referer", "https://www.google.com/recaptcha/api2/anchor?k=6LddFxQTAAAAAIv-3vX-Z4IxTqQMUNYeGl" +
                        "Exx8cc&co=aHR0cHM6Ly90ZXN0LWFjY291bnRzLmphY2tzb25oZXdpdHQuY29tOjQ0Mw..&hl=en&v=r" +
                        "20160706101427&size=normal&cb=e19yhq1gqp7i"));
            yield return request33;
            request33 = null;

            WebTestRequest request34 = new WebTestRequest("https://fonts.gstatic.com/s/roboto/v15/mnpfi9pxYH-Go5UiibESIqCWcynf_cDxXwCLxiixG1" +
                    "c.ttf");
            request34.Headers.Add(new WebTestRequestHeader("Referer", "https://www.google.com/recaptcha/api2/anchor?k=6LddFxQTAAAAAIv-3vX-Z4IxTqQMUNYeGl" +
                        "Exx8cc&co=aHR0cHM6Ly90ZXN0LWFjY291bnRzLmphY2tzb25oZXdpdHQuY29tOjQ0Mw..&hl=en&v=r" +
                        "20160706101427&size=normal&cb=e19yhq1gqp7i"));
            yield return request34;
            request34 = null;
        }
    }
}
