// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MYJHSpecflow_.MyJHSignUp.BecomeATaPreparer.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Inquiry Form")]
    public partial class InquiryFormFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Inquiry Form.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Inquiry Form", "\tAs a user of Jackson Hewitt Website \r\n\tI want to be able to sign up for Jackson " +
                    "Hewitt preparation\r\n\tSo that I can become a tav preparer ", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Inquiry")]
        [NUnit.Framework.CategoryAttribute("regression")]
        [NUnit.Framework.CategoryAttribute("Browser:")]
        [NUnit.Framework.CategoryAttribute("Chrome")]
        [NUnit.Framework.TestCaseAttribute("Peter", "Parker", "501 N Cattleman Rd", "Little Rock", "72211", "AR", "9243130150", "faizul.islam@jtax.com", "faizul.islam@jtax.com", "Trade Show", "Expo", "Other", null)]
        public virtual void Inquiry(string firstName, string lastName, string streetAddress, string city, string zipCode, string state, string contactNumber, string email, string reEnterEmail, string aboutJacksonHewitt, string specify, string interestInJacksonHewitt, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "regression",
                    "Browser:",
                    "Chrome"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Inquiry", @__tags);
#line 11
this.ScenarioSetup(scenarioInfo);
#line 12
testRunner.Given("that I am a Web user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 13
testRunner.When("I navigate to the become a tax preparer link from the home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 14
testRunner.Then(string.Format("I should be able to complete and submit inquiry  by providing the following infor" +
                        "mation {0}and{1}and{2}and{3}and{4}and{5}and{6}and{7}and{8}and{9}and{10}and{11}", firstName, lastName, streetAddress, city, zipCode, state, contactNumber, email, reEnterEmail, aboutJacksonHewitt, specify, interestInJacksonHewitt), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 15
testRunner.And("I should be shown the thank you page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
