// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace testdemo
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinClient uITaxYear2016MenuClient = this.UITaxYear2016MenuWindow.UIItemWindow.UITaxYear2016MenuClient;
            #endregion

            // Launch '%SystemRoot%\Microsoft.NET\Framework\v4.0.30319\RegAsm.exe' with arguments '/silent /nologo "c:\jhprofiler2016\JH.EF.ValidateXMLAgainstXSD.dll" >NUL'
            ApplicationUnderTest regAsmApplication = ApplicationUnderTest.Launch(this.RecordedMethod1Params.ExePath, this.RecordedMethod1Params.AlternateExePath, "/silent /nologo \"c:\\jhprofiler2016\\JH.EF.ValidateXMLAgainstXSD.dll\" >NUL");

            // Click 'Tax-Year 2016 Menu' client
            Mouse.Click(uITaxYear2016MenuClient, new Point(47, 270));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UITaxYear2016MenuWindow UITaxYear2016MenuWindow
        {
            get
            {
                if ((this.mUITaxYear2016MenuWindow == null))
                {
                    this.mUITaxYear2016MenuWindow = new UITaxYear2016MenuWindow();
                }
                return this.mUITaxYear2016MenuWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UITaxYear2016MenuWindow mUITaxYear2016MenuWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Launch '%SystemRoot%\Microsoft.NET\Framework\v4.0.30319\RegAsm.exe' with arguments '/silent /nologo "c:\jhprofiler2016\JH.EF.ValidateXMLAgainstXSD.dll" >NUL'
        /// </summary>
        public string ExePath = "C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\RegAsm.exe";
        
        /// <summary>
        /// Launch '%SystemRoot%\Microsoft.NET\Framework\v4.0.30319\RegAsm.exe' with arguments '/silent /nologo "c:\jhprofiler2016\JH.EF.ValidateXMLAgainstXSD.dll" >NUL'
        /// </summary>
        public string AlternateExePath = "%SystemRoot%\\Microsoft.NET\\Framework\\v4.0.30319\\RegAsm.exe";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITaxYear2016MenuWindow : WinWindow
    {
        
        public UITaxYear2016MenuWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Tax-Year 2016 Menu";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "JHLaunchClass01";
            this.WindowTitles.Add("Tax-Year 2016 Menu");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "500";
            this.WindowTitles.Add("Tax-Year 2016 Menu");
            #endregion
        }
        
        #region Properties
        public WinClient UITaxYear2016MenuClient
        {
            get
            {
                if ((this.mUITaxYear2016MenuClient == null))
                {
                    this.mUITaxYear2016MenuClient = new WinClient(this);
                    #region Search Criteria
                    this.mUITaxYear2016MenuClient.WindowTitles.Add("Tax-Year 2016 Menu");
                    #endregion
                }
                return this.mUITaxYear2016MenuClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUITaxYear2016MenuClient;
        #endregion
    }
}
