//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prespect_Streest_Tets {
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    
    
    public class POSTCoded : WebTest {
        
        public POSTCoded() {
            this.Context.Add("WebServer1", "https://test-prospects.jhnet.com");
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }
        
        public override IEnumerator<WebTestRequest> GetRequestEnumerator() {
            WebTestRequest request1 = new WebTestRequest((this.Context["WebServer1"].ToString() + "/Prospects/v1/Prospects/"));
            request1.Method = "POST";
            request1.ExpectedHttpStatusCode = 201;
            StringHttpBody request1Body = new StringHttpBody();
            request1Body.ContentType = "application/json";
            request1Body.InsertByteOrderMark = false;
            request1Body.BodyString = @"{
  ""DateOfBirth"": ""1986-05-02T00:00:00"",
  ""EmailAddress"": ""Redfreeman@gmail.com"",
  ""FirstName"": ""Red"",
  ""FullSSN"": ""012345678"",
  ""LastName"": ""Freeman"",
  ""MiddleName"": """",
  ""PhoneNumber"": ""2125565566"",
  ""PhoneType"": ""Mobile"",
  ""SourceDescription"": ""Appointment Scheduler "",
  ""SourceName"": ""Eloquaal""
}
";
            request1.Body = request1Body;
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest((this.Context["WebServer1"].ToString() + "/Prospects/v1/Prospects/"));
            request2.Method = "POST";
            request2.ExpectedResponseUrl = "201";
            StringHttpBody request2Body = new StringHttpBody();
            request2Body.ContentType = "application/json";
            request2Body.InsertByteOrderMark = false;
            request2Body.BodyString = @"{
  ""DateOfBirth"": ""1975-08-15T00:00:00"",
  ""EmailAddress"": ""Ron.crest@yahoo.com"",
  ""FirstName"": ""Ron"",
  ""Last4SSN"": ""1232"",
  ""LastName"": ""Crest"",
  ""MiddleName"": """",
  ""PhoneNumber"": ""2125557878"",
  ""PhoneType"": ""Work"",
  ""SourceName"": ""Eloquaal"",
  ""SourceDescription"": ""Email""
}
";
            request2.Body = request2Body;
            yield return request2;
            request2 = null;

            WebTestRequest request3 = new WebTestRequest((this.Context["WebServer1"].ToString() + "/Prospects/v1/Prospects/"));
            request3.Method = "POST";
            StringHttpBody request3Body = new StringHttpBody();
            request3Body.ContentType = "application/json";
            request3Body.InsertByteOrderMark = false;
            request3Body.BodyString = @"{
  ""DateOfBirth"": ""1980-09-09T00:00:00"",
  ""EmailAddress"": ""jimmyabout@aol.com"",
  ""FirstName"": ""Jimmy"",
  ""FullSSN"": null,
  ""Last4SSN"": ""1234"",
  ""LastName"": ""About"",
  ""Metadata"": null,
  ""MiddleName"": null,
  ""PhoneNumber"": """",
  ""PhoneType"": null,
  ""SourceDescription"": ""null"",
  ""SourceName"": ""nill"",
}";
            request3.Body = request3Body;
            yield return request3;
            request3 = null;

            WebTestRequest request4 = new WebTestRequest((this.Context["WebServer1"].ToString() + "/Prospects/v1/Prospects/"));
            request4.Method = "POST";
            StringHttpBody request4Body = new StringHttpBody();
            request4Body.ContentType = "application/json";
            request4Body.InsertByteOrderMark = false;
            request4Body.BodyString = @"{
  ""DateOfBirth"": ""1975-08-15T00:00:00"",
  ""EmailAddress"": ""Bob.crest@yahoo.com"",
  ""FirstName"": ""Bob"",
  ""Last4SSN"": ""1232"",
  ""LastName"": ""Crest"",
  ""MiddleName"": """",
  ""PhoneNumber"": ""2125557878"",
  ""PhoneType"": ""Work"",
  ""SourceName"": ""Email"",
  ""SourceDescription"": ""Eloquaa""
}
";
            request4.Body = request4Body;
            yield return request4;
            request4 = null;
        }
    }
}
