//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prespect_Streest_Tets
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;


    public class WebTest2Coded : WebTest
    {

        public WebTest2Coded()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            WebTestRequest request1 = new WebTestRequest("https://test-prospects.jhnet.com/Prospects/v1/Prospects/");
            request1.Method = "POST";
            request1.Encoding = System.Text.Encoding.GetEncoding("utf-8");
            StringHttpBody request1Body = new StringHttpBody();
            request1Body.ContentType = "application/json";
            
            request1Body.InsertByteOrderMark = false;
            request1Body.BodyString = @"{
  ""DateOfBirth"": ""1975-03-02T00:00:00"",
  ""EmailAddress"": ""harley1212-mcguire@aol.com"",
  ""FirstName"": ""Harley"",
  ""Last4SSN"": ""7676"",
  ""LastName"": ""McGuireOkZ"",
  ""MiddleName"": """",
  ""PhoneNumber"": ""8005551212"",
  ""PhoneType"": ""Work"",
  ""SourceDescription"": ""Website1 Desc"",
  ""SourceName"": ""641ZZbsite11""
}
";
            request1.Body = request1Body;
            yield return request1;
            request1 = null;
        }
    }
}
