//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAndLoadTestProject14 {
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;
    
    
    public class WebTest1Coded : WebTest {
        
        public WebTest1Coded() {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }
        
        public override IEnumerator<WebTestRequest> GetRequestEnumerator() {
            // Initialize validation rules that apply to all requests in the WebTest
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low)) {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low)) {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            WebTestRequest request1 = new WebTestRequest("https://www2.jacksonhewitt.com/");
            WebTestRequest request1Dependent1 = new WebTestRequest("https://www2.jacksonhewitt.com/Content/Fonts/Lato/fonts/lato-v11-latin-300.eot");
            request1Dependent1.Headers.Add(new WebTestRequestHeader("Referer", "https://www2.jacksonhewitt.com/"));
            request1Dependent1.QueryStringParameters.Add("", "", false, false);
            request1.DependentRequests.Add(request1Dependent1);
            WebTestRequest request1Dependent2 = new WebTestRequest("https://www2.jacksonhewitt.com/Content/Fonts/Lato/fonts/lato-v11-latin-300.woff");
            request1Dependent2.Headers.Add(new WebTestRequestHeader("Referer", "https://www2.jacksonhewitt.com/"));
            request1.DependentRequests.Add(request1Dependent2);
            WebTestRequest request1Dependent3 = new WebTestRequest("https://www2.jacksonhewitt.com/Content/Fonts/Lato/fonts/lato-v11-latin-regular.eo" +
                    "t");
            request1Dependent3.Headers.Add(new WebTestRequestHeader("Referer", "https://www2.jacksonhewitt.com/"));
            request1Dependent3.QueryStringParameters.Add("", "", false, false);
            request1.DependentRequests.Add(request1Dependent3);
            WebTestRequest request1Dependent4 = new WebTestRequest("https://www2.jacksonhewitt.com/Content/Fonts/Lato/fonts/lato-v11-latin-italic.eot" +
                    "");
            request1Dependent4.Headers.Add(new WebTestRequestHeader("Referer", "https://www2.jacksonhewitt.com/"));
            request1Dependent4.QueryStringParameters.Add("", "", false, false);
            request1.DependentRequests.Add(request1Dependent4);
            WebTestRequest request1Dependent5 = new WebTestRequest("https://www2.jacksonhewitt.com/Content/Fonts/Lato/fonts/lato-v11-latin-700.eot");
            request1Dependent5.Headers.Add(new WebTestRequestHeader("Referer", "https://www2.jacksonhewitt.com/"));
            request1Dependent5.QueryStringParameters.Add("", "", false, false);
            request1.DependentRequests.Add(request1Dependent5);
            WebTestRequest request1Dependent6 = new WebTestRequest("https://bat.r.msn.com/action-uic/0");
            request1Dependent6.Headers.Add(new WebTestRequestHeader("Referer", "https://www2.jacksonhewitt.com/"));
            request1Dependent6.QueryStringParameters.Add("ti", "5176460", false, false);
            request1Dependent6.QueryStringParameters.Add("Ver", "2", false, false);
            request1Dependent6.QueryStringParameters.Add("mid", "a3c8f0b2-98a7-6b4d-1ad5-801533c99361", false, false);
            request1Dependent6.QueryStringParameters.Add("evt", "pageLoad", false, false);
            request1Dependent6.QueryStringParameters.Add("pi", "576086242", false, false);
            request1Dependent6.QueryStringParameters.Add("lg", "en-US", false, false);
            request1Dependent6.QueryStringParameters.Add("sw", "1600", false, false);
            request1Dependent6.QueryStringParameters.Add("sh", "900", false, false);
            request1Dependent6.QueryStringParameters.Add("sc", "24", false, false);
            request1Dependent6.QueryStringParameters.Add("tl", "Jackson+Hewitt+%c2%ae", false, false);
            request1Dependent6.QueryStringParameters.Add("p", "https%3A%2F%2Fwww2.jacksonhewitt.com%2F", false, false);
            request1Dependent6.QueryStringParameters.Add("r", "", false, false);
            request1Dependent6.QueryStringParameters.Add("rn", "728967", false, false);
            request1.DependentRequests.Add(request1Dependent6);
            WebTestRequest request1Dependent7 = new WebTestRequest("https://bat.bing.com/action/0");
            request1Dependent7.ThinkTime = 1;
            request1Dependent7.Headers.Add(new WebTestRequestHeader("Referer", "https://www2.jacksonhewitt.com/"));
            request1Dependent7.QueryStringParameters.Add("ti", "5176460", false, false);
            request1Dependent7.QueryStringParameters.Add("Ver", "2", false, false);
            request1Dependent7.QueryStringParameters.Add("mid", "a3c8f0b2-98a7-6b4d-1ad5-801533c99361", false, false);
            request1Dependent7.QueryStringParameters.Add("evt", "pageLoad", false, false);
            request1Dependent7.QueryStringParameters.Add("pi", "576086242", false, false);
            request1Dependent7.QueryStringParameters.Add("lg", "en-US", false, false);
            request1Dependent7.QueryStringParameters.Add("sw", "1600", false, false);
            request1Dependent7.QueryStringParameters.Add("sh", "900", false, false);
            request1Dependent7.QueryStringParameters.Add("sc", "24", false, false);
            request1Dependent7.QueryStringParameters.Add("tl", "Jackson+Hewitt+%c2%ae", false, false);
            request1Dependent7.QueryStringParameters.Add("p", "https%3A%2F%2Fwww2.jacksonhewitt.com%2F", false, false);
            request1Dependent7.QueryStringParameters.Add("r", "", false, false);
            request1Dependent7.QueryStringParameters.Add("rn", "844919", false, false);
            request1.DependentRequests.Add(request1Dependent7);
            WebTestRequest request1Dependent8 = new WebTestRequest("https://www2.jacksonhewitt.com/Content/Fonts/font-awesome/fonts/fontawesome-webfo" +
                    "nt.eot");
            request1Dependent8.Headers.Add(new WebTestRequestHeader("Referer", "https://www2.jacksonhewitt.com/"));
            request1Dependent8.QueryStringParameters.Add("", "", false, false);
            request1.DependentRequests.Add(request1Dependent8);
            WebTestRequest request1Dependent9 = new WebTestRequest("https://www2.jacksonhewitt.com/Content/Fonts/VarelaRound/fonts/varela-round-v6-la" +
                    "tin-regular.eot");
            request1Dependent9.Headers.Add(new WebTestRequestHeader("Referer", "https://www2.jacksonhewitt.com/"));
            request1Dependent9.QueryStringParameters.Add("", "", false, false);
            request1.DependentRequests.Add(request1Dependent9);
            yield return request1;
            request1 = null;

            WebTestRequest request2 = new WebTestRequest("https://bs.serving-sys.com/Serving");
            request2.Headers.Add(new WebTestRequestHeader("Referer", "https://www2.jacksonhewitt.com/"));
            request2.QueryStringParameters.Add("cn", "ot", false, false);
            request2.QueryStringParameters.Add("onetagid", "4398", false, false);
            request2.QueryStringParameters.Add("dispType", "js", false, false);
            request2.QueryStringParameters.Add("sync", "0", false, false);
            request2.QueryStringParameters.Add("pageurl", "$$https%3A//www2.jacksonhewitt.com/$$", false, false);
            request2.QueryStringParameters.Add("ns", "0", false, false);
            request2.QueryStringParameters.Add("rnd", "4798338453898611", false, false);
            yield return request2;
            request2 = null;
        }
    }
}
